= Introduction

An add-on for https://www.atlassian.com/software/bitbucket/server[Atlassian Bitbucket Server] to render AsciiDoc files in the source view panel.

= Installation

The plugin is available in the https://marketplace.atlassian.com/plugins/org.christiangalsterer.stash-filehooks-plugin[Atlassian Marketplace] and can be installed directly in Bitbucket Server using the Universal Plugin Manager (UPM), see https://marketplace.atlassian.com/plugins/org.christiangalsterer.bitbucket-asciidoc-plugin#tabs-installation[here] for details.

= Releases

== 1.x.x

The 1.x.x versions were originally reserved for Bitbucket Server &lt; 4.0.0. No releases planned anymore.

== 2.x.x

The 2.x.x versions are for Bitbucket Server &gt;= 4.0.0 and &lt; 5.0.0

=== 2.4.0 (2017-10-28)

This version includes the following changes:

* https://github.com/christiangalsterer/bitbucket-asciidoc-plugin/issues/9[Improved support for file include directives]
* Support for `env-bitbucket` and `env`:`bitbucket` document attributes for conditional rendering, see also http://asciidoctor.org/docs/user-manual/#conditional-preprocessor-directives

=== 2.3.2 (2016-11-13)

This version includes the following changes:

* Fix: Image includes not correctly rendered for non-default branches

=== 2.3.1 (2016-06-10)

This version includes the following changes:

* Fix: Correct handling of file extensions

=== 2.3.0 (2016-02-13)

This version includes the following changes:

* Syntax highlighting for AsciiMath and LaTeX syntax using https://www.mathjax.org[MathJax]. Thanks to https://github.com/stuwhite[stuwhite].
* Update to asciidoctor.js 1.5.4
* Update to highlight.js 9.1.0

=== 2.2.0 (2016-02-06)

This version includes the following changes:

* Rendering of relative image locations

=== 2.1.0 (2016-01-06)

This version includes the following changes:

* Syntax highlighting using https://highlightjs.org[highlight.js]
* Improved layout to be closer to Bitbucket Server Markdown support

=== 2.0.0 (2015-12-21)

This is the first release of the add-on. It provides the following features:

* Rendering of AsciiDoc documents in the source view
* Usage of https://github.com/asciidoctor/asciidoctor.js[asciidoctor.js 1.5.3-preview.5]

== 3.x.x

The 3.x.x versions are for Bitbucket Server &gt;= 5.0.0

= License

[source]
----
   Copyright 2015 Christian Galsterer

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
----